export default {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_REQUEST_REJECTED: 'AUTH_REQUEST_REJECTED',
  AUTH_REQUEST_FULLFILED: 'AUTH_REQUEST_FULLFILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGOUT_FULLFILED: 'AUTH_LOGOUT_FULLFILED',
  AUTH_LOGOUT_REJECTED: 'AUTH_LOGOUT_REJECTED',
};
