export default {
  COURSE_SET: "COURSE_SET",
  COURSE_STATS_REQUEST: "COURSE_STATS_REQUEST",
  COURSE_STATS_REQUEST_FULFILLED: "COURSE_STATS_REQUEST_FULFILLED",
  COURSE_STATS_REQUEST_REJECTED: "COURSE_STATS_REQUEST_REJECTED",
  COURSE_POST_STAT: "COURSE_POST_STAT",
  COURSE_REMOVE_STAT: "COURSE_REMOVE_STAT",
  COURSE_GET_COMMENTS: "COURSE_GET_COMMENTS",
  COURSE_GET_COMMENTS_FULFILLED: "COURSE_GET_COMMENTS_FULFILLED",
  COURSE_GET_COMMENTS_REJECTED: "COURSE_GET_COMMENTS_REJECTED",
  COURSE_POST_COMMENT_REJECTED: "COURSE_POST_COMMENT_REJECTED",
  COURSE_POST_COMMENT_FULFILLED: "COURSE_POST_COMMENT_FULFILLED",
  COURSE_POST_COMMENT: "COURSE_POST_COMMENT"
};
