export default {
  TEACHER_SET: "TEACHER_SET",
  TEACHER_STATS_REQUEST: "TEACHER_STATS_REQUEST",
  TEACHER_STATS_REJECTED: "TEACHER_STATS_REJECTED",
  TEACHER_STATS_FULLFILED: "TEACHER_STATS_FULLFILED",
  TEACHER_POST_STAT: "TEACHER_POST_STAT",
  TEACHER_POST_STAT_REJECTED: "TEACHER_POST_STAT_REJECTED",
  TEACHER_POST_STAT_FULFILLED: "TEACHER_POST_STAT_FULFILLED"
};
