export default {
  TEACHER_SET: 'TEACHER_SET',
  TEACHER_STATS_REQUEST: 'TEACHER_STATS_REQUEST',
  TEACHER_STATS_REJECTED: 'TEACHER_STATS_REJECTED',
  TEACHER_STATS_FULLFILED: 'TEACHER_STATS_FULLFILED',
};
