export default {
  TEACHER_SET: "TEACHER_SET",
  TEACHER_STATS_REQUEST: "TEACHER_STATS_REQUEST",
  TEACHER_STATS_REJECTED: "TEACHER_STATS_REJECTED",
  TEACHER_STATS_FULLFILED: "TEACHER_STATS_FULLFILED",
  TEACHER_POST_STAT: "TEACHER_POST_STAT",
  TEACHER_REMOVE_STAT: "TEACHER_REMOVE_STAT",
  TEACHER_GET_COMMENTS: "TEACHER_GET_COMMENTS",
  TEACHER_GET_COMMENTS_FULFILLED: "TEACHER_GET_COMMENTS_FULFILLED",
  TEACHER_GET_COMMENTS_REJECTED: "TEACHER_GET_COMMENTS_REJECTED",
  TEACHER_POST_COMMENT_REJECTED: "TEACHER_POST_COMMENT_REJECTED",
  TEACHER_POST_COMMENT_FULFILLED: "TEACHER_POST_COMMENT_FULFILLED",
  TEACHER_POST_COMMENT: "TEACHER_POST_COMMENT"
};
