export default {
  USER_GET_VOTES: "USER_GET_VOTES",
  USER_GET_VOTES_FULFILLED: "USER_GET_VOTES_FULFILLED",
  USER_GET_VOTES_REJECTED: "USER_GET_VOTES_REJECTED",
  USER_SEND_STAT: "USER_SEND_STAT",
  USER_SEND_STAT_REJECTED: "USER_SEND_STAT_REJECTED",
  USER_SEND_STAT_FULFILLED: "USER_SEND_STAT_FULFILLED",
  USER_REMOVE_STAT: "USER_REMOVE_STAT",
  USER_REMOVE_STAT_REJECTED: "USER_REMOVE_STAT_REJECTED",
  USER_REMOVE_STAT_FULFILLED: "USER_REMOVE_STAT_FULFILLED"
};
